# Generated by Django 4.2.4 on 2023-09-03 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nric', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_nric', message='NRIC must be in the format: ^[STFGstfg]\\d{7}[a-zA-Z]$', regex='^[STFGstfg]\\d{7}[a-zA-Z]$')])),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/')),
                ('age', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_contact_number', message='Contact number must be in the format: +65 12345678', regex='^\\+65 \\d{8}$')])),
                ('address', models.CharField(max_length=255)),
                ('valid_license', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account_creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
