# Generated by Django 4.2.5 on 2023-09-06 08:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nric', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_nric', message='NRIC must be in the format: ^[STFGstfg]\\d{7}[a-zA-Z]$', regex='^[STFGstfg]\\d{7}[a-zA-Z]$')])),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/')),
                ('age', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_contact_number', message='Contact number must be in the format: +65 12345678', regex='^\\+65 \\d{8}$')])),
                ('address', models.CharField(max_length=255)),
                ('valid_license', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account_creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarSale',
            fields=[
                ('sale_id', models.CharField(editable=False, max_length=41, primary_key=True, serialize=False)),
                ('viewing_date', models.DateField()),
                ('viewing_time', models.TimeField()),
                ('is_sold', models.BooleanField(default=False)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('cancel_apt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('complaint_outcome', models.CharField(choices=[('PEN', 'Pending'), ('RES', 'Resolved'), ('UR', 'Unresolved')], max_length=3)),
                ('complaint_description', models.TextField()),
                ('date_log', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fine_description', models.TextField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_type', models.IntegerField(choices=[(1, 'THIRD_PARTY'), (2, 'THIRD_PARTY_FIRE_AND_THEFT'), (3, 'Comprehensive')], default=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('transaction_id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('early_termination', models.BooleanField(default=False)),
                ('refunds', models.IntegerField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('rental_start_date', models.DateTimeField()),
                ('rental_end_date', models.DateTimeField()),
                ('rental_status', models.CharField(choices=[('NC', 'Not collected'), ('CO', 'Collected'), ('RE', 'Returned'), ('OD', 'Over Due')], max_length=2)),
                ('customer_nric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
