# Generated by Django 4.2.5 on 2023-09-06 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='registration_no',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_policy', to='dealer.car'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='transaction_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_policy', to='customers.rental'),
        ),
        migrations.AddField(
            model_name='fine',
            name='customer_nric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_fines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='registration_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_fines', to='dealer.car'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='customer_nric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carsale',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dealer.car'),
        ),
        migrations.AddField(
            model_name='carsale',
            name='customer_nric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_booking', to=settings.AUTH_USER_MODEL),
        ),
    ]
