# Generated by Django 4.2.4 on 2023-09-04 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('transaction_id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('early_termination', models.BooleanField(default=False)),
                ('refunds', models.IntegerField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('rental_start_date', models.DateTimeField()),
                ('rental_end_date', models.DateTimeField()),
                ('rental_status', models.CharField(choices=[('NC', 'Not collected'), ('CO', 'Collected'), ('RE', 'Returned'), ('OD', 'Over Due')], max_length=2)),
                ('customer_nric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_receipts', to='customers.customeraccount')),
            ],
        ),
    ]
