# Generated by Django 4.2.4 on 2023-09-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rentals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rentals',
            new_name='Rental',
        ),
    ]
