# Generated by Django 4.2.4 on 2023-09-04 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_rentals_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('complaint_outcome', models.CharField(choices=[('PEN', 'Pending'), ('RES', 'Resolved'), ('UR', 'Unresolved')], max_length=3)),
                ('complaint_description', models.TextField()),
                ('customer_nric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_complaints', to='customers.customeraccount')),
            ],
        ),
    ]
