# Generated by Django 4.2.5 on 2023-09-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rental_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsale',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
