# Generated by Django 4.2.4 on 2023-09-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_alter_car_is_avail'),
        ('customers', '0005_complaint_date_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='customer_nric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_complaints', to='customers.customeraccount'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_log',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer_nric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_receipts', to='customers.customeraccount'),
        ),
        migrations.CreateModel(
            name='CarSale',
            fields=[
                ('sale_id', models.CharField(editable=False, max_length=41, primary_key=True, serialize=False)),
                ('viewing_date', models.DateField()),
                ('viewing_time', models.TimeField()),
                ('is_sold', models.BooleanField(default=False)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('cancel_apt', models.BooleanField(default=False)),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dealer.car')),
                ('customer_nric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_booking', to='customers.customeraccount')),
            ],
        ),
    ]
