# Generated by Django 4.2.4 on 2023-09-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_alter_car_is_avail'),
        ('customers', '0006_alter_complaint_customer_nric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fine_description', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('customer_nric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_fines', to='customers.customeraccount')),
                ('registration_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_fines', to='dealer.car')),
            ],
        ),
    ]
