# Generated by Django 4.2.4 on 2023-09-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_alter_car_is_avail'),
        ('customers', '0007_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_type', models.IntegerField(choices=[(1, 'THIRD_PARTY'), (2, 'THIRD_PARTY_FIRE_AND_THEFT'), (3, 'Comprehensive')], default=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('registration_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_insurance', to='dealer.car')),
                ('transaction_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_insurance', to='customers.rental')),
            ],
        ),
    ]
