# Generated by Django 4.2.4 on 2023-09-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0005_car_vehicle_image_rentallisting'),
        ('customers', '0008_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='registration_no',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_policy', to='dealer.car'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='transaction_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_policy', to='customers.rental'),
        ),
    ]
