# Generated by Django 4.2.4 on 2023-09-04 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('registration_no', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_license_plate', message='Please enter a valid Singapore registered license plate', regex='^S[A-Z]{2}[0-9]{1,4}[A-Z]$')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('road_tax_expiry', models.DateField()),
                ('coe_expiry', models.DateField()),
                ('colour', models.CharField(max_length=20)),
                ('seat_capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(2)])),
                ('fuel_consumption', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('transmission', models.CharField(choices=[('auto', 'automatic transmission'), ('manual', 'manual transmission')], max_length=6)),
                ('no_of_owners', models.PositiveSmallIntegerField()),
                ('vehicle_type', models.CharField(choices=[('hatchback', 'Hatchback'), ('sports', 'Sports car'), ('sedan', 'Sedan'), ('mpv', 'family car')], max_length=10)),
                ('engine_cap', models.PositiveIntegerField()),
                ('registration_date', models.DateField()),
                ('depreciation', models.PositiveSmallIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('road_tax_amount', models.PositiveSmallIntegerField()),
                ('is_avail', models.BooleanField()),
            ],
        ),
    ]
