# Generated by Django 4.2.5 on 2023-09-06 08:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('registration_no', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_license_plate', message='Please enter a valid Singapore registered license plate', regex='^S[A-Z]{2}[0-9]{1,4}[A-Z]$')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('road_tax_expiry', models.DateField()),
                ('coe_expiry', models.DateField()),
                ('colour', models.CharField(max_length=20)),
                ('seat_capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(2)])),
                ('fuel_consumption', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('transmission', models.CharField(choices=[('auto', 'automatic transmission'), ('manual', 'manual transmission')], max_length=6)),
                ('no_of_owners', models.PositiveSmallIntegerField()),
                ('vehicle_type', models.CharField(choices=[('hatchback', 'Hatchback'), ('sports', 'Sports car'), ('sedan', 'Sedan'), ('mpv', 'family car')], max_length=10)),
                ('engine_cap', models.PositiveIntegerField()),
                ('registration_date', models.DateField()),
                ('depreciation', models.PositiveSmallIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('road_tax_amount', models.PositiveSmallIntegerField()),
                ('is_avail', models.BooleanField(default=True)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='car_pics')),
            ],
        ),
        migrations.CreateModel(
            name='SaleListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_price', models.PositiveBigIntegerField()),
                ('listing_date', models.DateField(auto_now_add=True)),
                ('car_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_post', to='dealer.car')),
            ],
        ),
        migrations.CreateModel(
            name='RentalListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('listing_date', models.DateField(auto_now_add=True)),
                ('drive_to_malaysia', models.BooleanField(default=True)),
                ('car_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_post', to='dealer.car')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField()),
                ('sale_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_model', to='customers.carsale')),
            ],
        ),
    ]
