# Generated by Django 4.2.4 on 2023-09-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_avail',
            field=models.BooleanField(default=True),
        ),
    ]
