# Generated by Django 4.2.4 on 2023-09-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_insurance'),
        ('dealer', '0003_alter_car_is_avail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField()),
                ('sale_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_model', to='customers.carsale')),
            ],
        ),
    ]
