# Generated by Django 4.2.4 on 2023-09-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_pics'),
        ),
        migrations.CreateModel(
            name='RentalListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('listing_date', models.DateField(auto_now_add=True)),
                ('drive_to_malaysia', models.BooleanField(default=True)),
                ('car_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_post', to='dealer.car')),
            ],
        ),
    ]
