# Generated by Django 4.2.4 on 2023-09-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0005_car_vehicle_image_rentallisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentallisting',
            name='car_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_post', to='dealer.car'),
        ),
        migrations.CreateModel(
            name='SaleListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_price', models.PositiveBigIntegerField()),
                ('listing_date', models.DateField(auto_now_add=True)),
                ('car_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_post', to='dealer.car')),
            ],
        ),
    ]
